global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'prashantsingh15749@gmail.com'
  smtp_auth_username: 'prashantsingh15749@gmail.com'
  smtp_auth_identity: 'prashantsingh15749@gmail.com'
  smtp_auth_password: 'yawdktmpuzeaezxh'

route:
  group_by: ['alertname', 'cluster', 'job', 'env']
  repeat_interval: 24h
  group_interval: 5m
  # capture All
  receiver: 'ops'
  routes:
    # capture All WARN to the 'warning' with P3
    - match:
        severity: warning
      receiver: admin

receivers:
- name: admin
  email_configs:
  - to: 'prashantsingh15749@gmail.com'


- name: ops
  email_configs:
  - to: 'prashantnitt07@gmail.com'

