global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '${SMTP_FROM}'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_identity: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'

route:
  group_by: ['alertname', 'cluster', 'job', 'env']
  repeat_interval: 24h
  group_interval: 5m
  # capture All
  receiver: 'ops'
  routes:
    # capture All WARN to the 'warning' with P3
    - match:
        severity: warning
      receiver: admin
    - match:
        severity: critical
      receiver:  lead

receivers:
- name: admin
  email_configs:
  - to: '${ALERT_EMAIL_TO}'
- name: lead
  email_configs:
  - to: '${ALERT_EMAIL_TO}'


- name: ops
  email_configs:
  - to: '${ALERT_EMAIL_TO}'

